/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class src_controller_Controller */

#ifndef _Included_src_controller_Controller
#define _Included_src_controller_Controller
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     src_controller_Controller
 * Method:    update_text_descriptors
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_src_controller_Controller_update_1text_1descriptors
  (JNIEnv *, jobject, jint);

/*
 * Class:     src_controller_Controller
 * Method:    update_image_descriptors
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_src_controller_Controller_update_1image_1descriptors
  (JNIEnv *, jobject, jint);

/*
 * Class:     src_controller_Controller
 * Method:    update_sound_descriptors
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_src_controller_Controller_update_1sound_1descriptors
  (JNIEnv *, jobject, jint);

/*
 * Class:     src_controller_Controller
 * Method:    search_by_file
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_src_controller_Controller_search_1by_1file
  (JNIEnv *, jobject, jstring);

/*
 * Class:     src_controller_Controller
 * Method:    search_by_keyword
 * Signature: ([Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_src_controller_Controller_search_1by_1keyword
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     src_controller_Controller
 * Method:    login
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_src_controller_Controller_login
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
