/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class src_Controller_Controller */

#ifndef _Included_src_Controller_Controller
#define _Included_src_Controller_Controller
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     src_Controller_Controller
 * Method:    search_by_file
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_src_Controller_Controller_search_1by_1file
  (JNIEnv *, jobject, jobject);

/*
 * Class:     src_Controller_Controller
 * Method:    update_descriptors
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_src_Controller_Controller_update_1descriptors
  (JNIEnv *, jobject, jobject);

/*
 * Class:     src_Controller_Controller
 * Method:    error_config_file
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_src_Controller_Controller_error_1config_1file
  (JNIEnv *, jobject);

/*
 * Class:     src_Controller_Controller
 * Method:    search_by_keyword
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_src_Controller_Controller_search_1by_1keyword
  (JNIEnv *, jobject, jstring);

/*
 * Class:     src_Controller_Controller
 * Method:    modif_config
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_src_Controller_Controller_modif_1config
  (JNIEnv *, jobject);

/*
 * Class:     src_Controller_Controller
 * Method:    generate_all_descriptors
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_src_Controller_Controller_generate_1all_1descriptors
  (JNIEnv *, jobject, jobject);

/*
 * Class:     src_Controller_Controller
 * Method:    reset_config
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_src_Controller_Controller_reset_1config
  (JNIEnv *, jobject);

/*
 * Class:     src_Controller_Controller
 * Method:    load_config
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_src_Controller_Controller_load_1config
  (JNIEnv *, jobject);

/*
 * Class:     src_Controller_Controller
 * Method:    change_password
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_src_Controller_Controller_change_1password
  (JNIEnv *, jobject);

/*
 * Class:     src_Controller_Controller
 * Method:    login
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_src_Controller_Controller_login
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
