/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class model_entities_QTILKernel */

#ifndef _Included_model_entities_QTILKernel
#define _Included_model_entities_QTILKernel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     model_entities_QTILKernel
 * Method:    update_text_descriptors
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_model_entities_QTILKernel_update_1text_1descriptors
  (JNIEnv *, jobject, jint);

/*
 * Class:     model_entities_QTILKernel
 * Method:    update_image_descriptors
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_model_entities_QTILKernel_update_1image_1descriptors
  (JNIEnv *, jobject, jint);

/*
 * Class:     model_entities_QTILKernel
 * Method:    update_sound_descriptors
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_model_entities_QTILKernel_update_1sound_1descriptors
  (JNIEnv *, jobject, jint);

/*
 * Class:     model_entities_QTILKernel
 * Method:    search_by_file
 * Signature: (Ljava/lang/String;)[[C
 */
JNIEXPORT jobjectArray JNICALL Java_model_entities_QTILKernel_search_1by_1file
  (JNIEnv *, jobject, jstring);

/*
 * Class:     model_entities_QTILKernel
 * Method:    search_by_keyword
 * Signature: ([Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_model_entities_QTILKernel_search_1by_1keyword
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
